### ISSUE TITLE
Feature Request: Copy Folder Permissions when generating a new folder

### ISSUE THREAD

**Issue by cjyoos** [looker-open-source/looker_deployer#101]
Or ... am I using this wrong?

I noticed that when I moved replicated a bunch of content to a new instance and the folders had to be created, none of the groups (which I had transferred) had access to the folders.  It seems like they just inherited the permissions from the shared (parent) folder.

**Comment by jannarobertson-bytecode** [comment]
@cjyoos correct, this would be a new feature request for Deployer; your request has been added to the backlog to aid in roadmap planning.
