### ISSUE TITLE
Getting error while using Looker Deployer 0.3.9

### ISSUE THREAD

**Issue by ramatejas** [looker-open-source/looker_deployer#115]
Using Gazer V 0.2.54 (also tried with V0.2.59 & 0.2.58) and Looker_Deployer V0.3.9. Getting the following error started this week only:

/var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client.rb:475:in `merge_content_type_if_body': uninitialized constant Faraday::UploadIO (NameError)
	from /var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client/dynamic.rb:149:in `invoke_remote'
	from /var/lib/gems/2.7.0/gems/looker-sdk-0.1.4/lib/looker-sdk/client/dynamic.rb:107:in `method_missing'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/modules/dashboard.rb:99:in `update_dashboard'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/commands/dashboard/import.rb:168:in `sync_dashboard'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/commands/dashboard/import.rb:66:in `block (2 levels) in execute'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/modules/filehelper.rb:88:in `read_file'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/commands/dashboard/import.rb:54:in `block in execute'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/modules/session.rb:249:in `with_session'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/commands/dashboard/import.rb:50:in `execute'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/lib/gzr/commands/dashboard.rb:78:in `import'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.54/exe/gzr:36:in `<top (required)>'
	from /usr/local/bin/gzr:[23](https://github.com/sharphealthcare/looker-clinical/actions/runs/4557253637/jobs/8083675952#step:4:24):in `load'
	from /usr/local/bin/gzr:23:in `<main>'
Modifying existing dashboard [35](https://github.com/sharphealthcare/looker-clinical/actions/runs/4557253637/jobs/8083675952#step:4:36) Emergency Department NDNQI Statistics in space 10

**Comment by AdamMinton** [comment]
Updated to API 4.0 per latest release - [v0.3.10](https://github.com/looker-open-source/looker_deployer/releases/tag/looker-deployer-v0.3.10)

Latest versions of Gazer, Looker Deployer, and Looker SDK should address the issue.
