### ISSUE TITLE
Dockerfile results in `method_missing` error

### ISSUE THREAD

**Issue by pgoslatara** [looker-open-source/looker_deployer#116]
I am currently deploying looker_deployer at a client and am following the README to create the Docker image where commands can be run. Unfortunately I keep getting the same error. I see issue #79 where a similar error message was reported, the solution in this case was to update the gazer version (this version is now outdated so this approach is not possible). Any ideas why I am getting this "undefined method `space'" error or steps I can take to debug?

Steps to repeat:
1. Initialise `looker.ini` with a "dev" target.
1. Run:
```bash
docker build -t ldeploy .
docker run ldeploy content export --env dev --ini looker.ini --debug --folders 12 --local-target ./export
```
Resulting logs:
```
{"levelname": "DEBUG", "module": "deploy_content_export", "funcName": "main", "message": "ini file", "ini": "looker.ini", "timestamp": "2023-04-03T13:47:19.176112Z"}
{"levelname": "INFO", "module": "deploy_content_export", "funcName": "main", "message": "Exporting content", "env": "dev", "folders": ["12"], "dashboards": null, "looks": null, "local_target": "./export", "timestamp": "2023-04-03T13:47:19.176343Z"}
{"levelname": "DEBUG", "module": "deploy_content_export", "funcName": "recurse_folders", "message": "recursive folder crawl status", "current_id": "12", "folder_name": "Marketing", "current_list": ["Marketing"], "timestamp": "2023-04-03T13:47:20.822746Z"}
{"levelname": "DEBUG", "module": "deploy_content_export", "funcName": "recurse_folders", "message": "going for recursion", "parent_id": "1", "timestamp": "2023-04-03T13:47:20.822962Z"}
{"levelname": "DEBUG", "module": "deploy_content_export", "funcName": "recurse_folders", "message": "recursive folder crawl status", "current_id": "1", "folder_name": "Shared", "current_list": ["Marketing", "Shared"], "timestamp": "2023-04-03T13:47:21.407126Z"}
{"levelname": "DEBUG", "module": "deploy_content_export", "funcName": "send_export", "message": "folder_list", "folder_id": "12", "list": ["Shared", "Marketing"], "timestamp": "2023-04-03T13:47:21.407325Z"}
/var/lib/gems/2.7.0/gems/looker-sdk-0.1.2/lib/looker-sdk/client/dynamic.rb:106:in `method_missing': undefined method `space' for #<LookerSDK::Client:0x000055e2e8ce4ed0> (NoMethodError)
        from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/modules/space.rb:65:in `query_space'
        from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/commands/space/export.rb:89:in `process_space'
        from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/commands/space/export.rb:83:in `block in execute'
        from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/modules/session.rb:249:in `with_session'
        from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/commands/space/export.rb:51:in `execute'
        from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/commands/space.rb:82:in `export'
        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /var/lib/gems/2.7.0/gems/gazer-0.2.59/exe/gzr:36:in `<top (required)>'
        from /usr/local/bin/gzr:23:in `load'
        from /usr/local/bin/gzr:23:in `<main>'
options: {"debug"=>true, "host"=>"<REDACTED>", "port"=>"19999", "ssl"=>true, "verify_ssl"=>true, "timeout"=>60, "force"=>false, "persistent"=>false, "client_id"=>"<REDACTED>", "client_secret"=>"<REDACTED>", "dir"=>"export/Shared"}
using options ["debug=>true", "host=><REDACTED>", "port=>19999", "ssl=>true", "verify_ssl=>true", "timeout=>60", "force=>false", "persistent=>false", "client_id=><REDACTED>", "dir=>export/Shared"]
API current_version 4.0
API versions ["3.0", "3.1", "4.0"]
connecting to ["api_endpoint=>https://<REDACTED>:19999/api/4.0", "connection_options=>{:ssl=>{:verify=>true, :verify_mode=>3}, :request=>{:timeout=>60}}", "user_agent=>Gazer 0.2.59", "client_id=><REDACTED>", "client_secret=><REDACTED>"]
check for connectivity: true
verify authentication: true
logout
```

Versions:
```bash
root@1b1a4454b1f5:/looker_deployer# ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
root@1b1a4454b1f5:/looker_deployer# gem -v
3.2.5
root@1b1a4454b1f5:/looker_deployer# gem list | grep "gazer"
gazer (0.2.59)
root@1b1a4454b1f5:/looker_deployer# gem list | grep "looker"
looker-sdk (0.1.2)
```

Dockerfile:
```bash
FROM python:3.9-slim

RUN apt update
RUN apt -y install ruby ruby-dev
RUN gem install gazer

RUN apt -y install git 
RUN git clone https://github.com/looker-open-source/looker_deployer.git --branch looker-deployer-v0.3.9

WORKDIR /looker_deployer

COPY looker.ini . 
RUN pip install -e .

ENTRYPOINT ["ldeploy"]
```

**Comment by pgoslatara** [comment]
Interestingly, downgrading the version of `gazer` does not result in this issue:
```bash
FROM python:3.9-slim

RUN apt update
RUN apt -y install ruby ruby-dev
RUN gem install gazer --version 0.2.58

RUN apt -y install git 
RUN git clone https://github.com/looker-open-source/looker_deployer.git --branch looker-deployer-v0.3.9

WORKDIR /looker_deployer

COPY looker.ini . 
RUN pip install -e .

VOLUME /export

ENTRYPOINT ["ldeploy"]
```

**Comment by jasonstinnett** [comment]
I'm experiencing this issue as well using `--branch mcramer_alerts`

`/var/lib/gems/2.7.0/gems/looker-sdk-0.1.2/lib/looker-sdk/client/dynamic.rb:106:in `method_missing': undefined method `space' for #<LookerSDK::Client:0x000055f04906ecc8> (NoMethodError)
	from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/modules/space.rb:65:in `query_space'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/commands/space/export.rb:89:in `process_space'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/commands/space/export.rb:83:in `block in execute'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/modules/session.rb:249:in `with_session'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/commands/space/export.rb:51:in `execute'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.59/lib/gzr/commands/space.rb:82:in `export'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /var/lib/gems/2.7.0/gems/gazer-0.2.59/exe/gzr:36:in `<top (required)>'
	from /usr/local/bin/gzr:23:in `load'
	from /usr/local/bin/gzr:23:in `<main>'`

The folder I'm exporting is within the Shared folder. In case it helps pinpoint the issue, I do see that the ldeploy command successfully creates a Shared folder within the directory passed via --local-target (though it is empty)

Specifying `gazer --version 0.2.58` in dockerfile fixed the issue for me as well, really appreciate your follow up comment with the workaround @pgoslatara

**Comment by AdamMinton** [comment]
Updated to API 4.0 per latest release - [v0.3.10](https://github.com/looker-open-source/looker_deployer/releases/tag/looker-deployer-v0.3.10) - should resolve issues.
