### ISSUE TITLE
Update API version to 4.0

### ISSUE THREAD

**Issue by sraghuvaran** [looker-open-source/looker_deployer#118]
Currently, deployer is using api 3.1 which is going to be deprecated on June 20. Please update it to use version 4

**Comment by drstrangelooker** [comment]
@JCPistell and @AdamMinton 

Gazer is at 0.3.5 already, which uses API 4.0. Do you do everything through gazer or do you do anything directly?

**Comment by sraghuvaran** [comment]
we use ldeploy for deploying folders to higher envs and looks like it is authenticating with 3.1 SDK

https://github.com/looker-open-source/looker_deployer/blob/31b1645f4e0946bbe295adb2cad6753210c14e6e/looker_deployer/utils/get_client.py#L32

**Comment by Prakhar260296** [comment]
We use looker_deployer for deploying folders/dashboards to higher environments and looks like it is authenticating with 3.1 SDK.
I get an error like this : 
AttributeError: module 'looker_sdk.sdk.api31.methods' has no attribute 'Looker40SDK'
So requesting to update the dependencies to use version 4.0

**Comment by sraghuvaran** [comment]
Can you please provide some details on how do I update it to use version 4.0. I still see get_client function is using 3.1 
@Prakhar260296

**Comment by Prakhar260296** [comment]
@sraghuvaran Even i face the same issue. 
@drstrangelooker @JCPistell @AdamMinton can you please look into this and provide some update here as we are quite near to the deprecation date of the api version 3.1 ?

**Comment by JCPistell** [comment]
I have not been involved in this project for years. Please stop tagging me.

**Comment by AdamMinton** [comment]
Updated to API 4.0 per latest release - [v0.3.10](https://github.com/looker-open-source/looker_deployer/releases/tag/looker-deployer-v0.3.10)
