### ISSUE TITLE
KeyError:‘results’ in deploy_code file stopping deployment -> Fix to try-except block?

### ISSUE THREAD

**Issue by brigitteq** [looker-open-source/looker_deployer#131]
@drstrangelooker I am getting a KeyError:‘results’ when trying to deploy hub code for just our QA stack.I’ve narrowed down the line of code to come from the deploy_code py file here (see pictured)

Can we submit a hotfix to update this line of code to skip this for QA via a try-except block instead?
![image](https://github.com/looker-open-source/looker_deployer/assets/63247731/ed716440-b121-4bc4-a15a-860b97cd2b13)

Also, can  you tell me what “results” is supposed to be looking for? I think this will always error for QA but we don’t want it to stop our hub code deployment.

**Comment by megfordpix** [comment]
We are also seeing this issue. It looks like the response json is returning  {'operations': [{'error': False}]}
I am implementing a work-around for this for now because our code appears to be deploying successfully, and the response that you are checking for here https://github.com/looker-open-source/looker_deployer/blob/main/looker_deployer/commands/deploy_code.py#L85 isn't used anywhere else in the code.

**Comment by brigitteq** [comment]
@megfordpix @drstrangelooker This error is actually related to the latest looker release. It was only erroring on our QA stack before since our QA stack gets the latest release first. 

I've updated what I know in the code to look for the api 4.0 where possible but still getting the above error. Any luck?

**Comment by drstrangelooker** [comment]
I'm changing this simply to 
```
results = r.json()["operations"][0]
```
So that the message will have either the result or the error: "false"

**Comment by megfordpix** [comment]
@drstrangelooker if the result is error: "false" does that indicate that the code has not synced?

**Comment by drstrangelooker** [comment]
No. That indicates that there were no errors. The error state is False.

**Comment by megfordpix** [comment]
@drstrangelooker Thanks! I figured, but just wanted to verify.
