### ISSUE TITLE
ERROR: Operation requires API v3.1, which is not available from this host

### ISSUE THREAD

**Issue by cathymathews-pie** [looker-open-source/looker_deployer#145]
I'm trying to download content from our instance, and initially, I was getting authentication errors. I uninstalled the looker-deployer package and reinstalled it, and now I get this error:
```
ERROR: Operation requires API v3.1, which is not available from this host
```

Is there an API 4.0 version available? I tried to search the code for the api reference, but I couldn't find anything, maybe it's in the gazer project? I didn't manually install gazer, is there a way to update that, if the API is updated there?

What's the best way to proceed on API 4.0 so I can download content from our Looker instance? Thanks!

**Comment by cathymathews-pie** [comment]
Hm, I see the API 4.0 in `get_client.py`, so it's something on my system. But I'm pretty sure Looker Deployer and Looker SDK are updated, I did a force reinstall, and these match the current packages on PyPI:
```(ldeploy) .... LookerDeployer % pip install looker-deployer                                                                 
Requirement already satisfied: looker-deployer in /Users/..../site-packages (0.3.11)
Requirement already satisfied: looker-sdk>=21.18.0 in /Users/..../site-packages (from looker-deployer) (23.16.0)
```

**Comment by vaibhavyadnik** [comment]
Hi @cathymathews-pie, I am also facing same issue. Did you get any solution on it ? Could you please help me if you found any solution ? 
Thanking you in advance

**Comment by k7ragav** [comment]
@cathymathews-pie Think you might need the latest version of `gazer` as well. I noticed that and I am currently in the process of getting my `gazer` package updated. You could give that a try and see. 
I think [this](https://github.com/looker-open-source/gzr/pull/154/files) was the version where they started making changes to accomadate API v4
