### ISSUE TITLE
Changed Slugs when Syncing Dashboards

### ISSUE THREAD

**Issue by megfordpix** [looker-open-source/looker_deployer#39]
I wrote a bash script that runs in Github Actions and uses Looker Deployer to sync dashboards and looks from our dev Looker instance to our prod Looker instance. We are not syncing the entire /Shared folder every time, we are syncing subfolders.

Internally, Looker Deployer is running a series of Gazer commands to accomplish that syncing. I am using the "deploy content" command in Looker Deployer. You can see the gazer commands that it runs here:
 https://github.com/llooker/looker_deployer/blob/master/looker_deployer/commands/deploy_content.py#L76
As you can see, it runs gazer with --force.

When we move an existing dashboard to a new subfolder, when we are syncing using --force, then **it seems like ** Gazer deletes the existing dashboard and sync a new copy. That delete moved the existing dashboard to the Trash folder. When this happens there is nothing listed in the "deleted by" column of some of the deleted dashboards in our Trash folder on our prod Looker instance, but I can't always duplicate this behavior. Sometimes Gazer just creates a new dashboard in the new folder without deleting the old dashboard, even though we are only moving the dashboards between different child folders of the parent folder we are syncing.

Gazer syncs dashboards **using a new slug ** because it detects that there is a dashboard with a duplicate slug in the Trash/in the other folder on the production Looker instance. You can see the code that does that here:
https://github.com/pixability/gazer/blob/master/lib/gzr/commands/dashboard/import.rb#L141

As a result, the dashboard slugs are out of sync sometimes and that breaks links in our dashboards on the prod instance.
 
Another note here: Since the team that runs the sync jobs doesn't have admin access to our  prod Looker instance, we can't ask them to make sure that dashboards are hard deleted. We need to have someone from the dev team manually intervene. 

If you seen this before, and am I accurately understanding what is happening? Can you tell me what the expected behavior is, and whether there are any workarounds for this?

**Comment by megfordpix** [comment]
This is the bash script I'm using, for reference:

folder_name=${1}
dest_folder_name=${2}
git clone $GIT_REPO && cd dashboards && git checkout -b new_branch
(rm -r ./"$folder_name" || :)
echo "exporting space $folder_name using gazer"
id=`gzr space ls "$folder_name" --host $DEV_HOST --fields id --plain`
echo "id $id"
for i in $id
do
    gzr space export $i --host $DEV_HOST --debug
    break
done
echo "export of space $folder_name successful \n\n"

git add .
(git commit -am "Export of folder $foldername" || :)
git checkout -
git merge new_branch master
(git push origin master:master || :)
(git branch -D new_branch || :)

fin=`ldeploy content --env prod --folders "$folder_name" --recursive --target-folder "$dest_folder_name" --debug`
echo "import of space $folder_name completed \n\n"

**Comment by michaelcramer** [comment]
@megfordpix is this still an issue you're able to reproduce?  If so, could you please respond with the Looker and python version you're using? Thanks!

**Comment by AdamMinton** [comment]
Closing ticket, feel free to re-open if issue persists.
