### ISSUE TITLE
cd looker_deployer does not work/is not available in home directory

### ISSUE THREAD

**Issue by chrissyflickerrandstad** [looker-open-source/looker_deployer#42]
I have installed looker-deployer multiple times with success and get a response from "ldeploy --version". I attempted to use the looker-deployer to migrate content and was not able to specify an environment or a folder to migrate to. This is not going to work for us. 

Looker-deployer has worked excellent in the past for us, but I am not stuck with it not working today, because we must stand up a new VM. The new VM install has not worked for me, yet.

**Comment by michaelcramer** [comment]
@chrissyflickerrandstad is this still an issue? you should have your looker.ini file set up with your different environments and be able to select one of them

**Comment by AdamMinton** [comment]
Closing ticket.
