### ISSUE TITLE
Dockerfile exits right after load

### ISSUE THREAD

**Issue by mikefoundation** [looker-open-source/looker_deployer#52]
Running into issue where docker file exits immediatley after loading. Both the Dockerfile and the pre-built image on dockerhub
<img width="1267" alt="Screen Shot 2021-09-21 at 6 18 21 PM" src="https://user-images.githubusercontent.com/91162423/134255221-50548059-984f-4637-a0d4-cf4415bc3f32.png">
.

**Comment by jannarobertson-bytecode** [comment]
@mikefoundation due to the age of the reported issue, we are closing it out.  Please open another issues if this remains unresolved and include the Looker + Deployer versions you're using.  Thanks!
