### ISSUE TITLE
Looker Import Target Folder

### ISSUE THREAD

**Issue by dliu9999** [looker-open-source/looker_deployer#55]
Hi,

Is it possible to implement a feature that allows for importing to a non-Shared folder? Currently, the target folder must start with "Shared," but I would like to import for example user 14's space in staging to user 14's space in prod. Thanks!

**Comment by jannarobertson-bytecode** [comment]
@dliu9999 This capability is now possible with the recent release of #91.  Thanks for your suggestion!
