### ISSUE TITLE
ldeploy on RedHat 8 - tries to validate SSL even though set to False in INI file

### ISSUE THREAD

**Issue by billweils** [looker-open-source/looker_deployer#57]
Hi.  I am working with looker-deployer on Red Hat 8.

It is failing on the following error

	 1: from /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (EE certificate key too weak) (OpenSSL::SSL::SSLError)

Appears to validate the SSL certificate in spite of looker.ini settings to False

Any help or insights would be appreciated

**Comment by michaelcramer** [comment]
@billweils is this still an issue? If so, could you please reply with the version of Looker and python you're using?  thanks!

**Comment by billweils** [comment]
No. No longer an issue - I have resolved by configuring a fully qualified SSL certificate on the system.

**Comment by AdamMinton** [comment]
Closing issue as resolved.
