### ISSUE TITLE
FR - Support for promoting user attributes between instances

### ISSUE THREAD

**Issue by ajcrutch** [looker-open-source/looker_deployer#60]
It sometimes occurs that a bit of LookML and/or a dashboard setting contains a reference to a user attribute. In those cases, the attribute must exist in all instances hosting that code and/or content. With the Looker Deplopyer, it is possible to promote content, but the user attribute which powers that content will need to be made manually. It would be useful to be able to "copy" a user attribute between instances. 

I would think a first iteration, and perhaps all that would really be necessary in the kinds of deployments using LDeploy, would be to move the "first page" of settings to the new instance. Group assignments of values or individual assignments would still need to be done manually. A default value, if it exists, could be promoted to the new instance.

**Comment by AdamMinton** [comment]
Hi Andy, This PR opened in October would address user attributes and group values between instances. https://github.com/looker-open-source/looker_deployer/pull/53

**Comment by AdamMinton** [comment]
Pull Request Completed and should be available now in this release - [0.3.4]( https://github.com/looker-open-source/looker_deployer/releases/tag/looker-deployer-v0.3.4)
