### ISSUE TITLE
execution expired (Faraday::ConnectionFailed)

### ISSUE THREAD

**Issue by scboyce** [looker-open-source/looker_deployer#78]
Hello, I have a strange situation in the Google Cloud running ldeploy.
First, my build:
>Starting with Ubuntu 20.04
apt install -y python3-dev
apt install -y python3-pip
apt install -y ruby
gem install gazer
pip3 install looker-sdk
pip3 install looker-deployer

When I do this build in my own personal CGP account "ldeploy content export folder" works perfectly fine.
>ldeploy content export --ini /u01/admin/conf/looker_environments.ini --env dev --folders 1 --local-target /u01/admin/data

When I do this build in my company's GCP account, the same command ends in a timeout:
[ldeploy-export-error.txt](https://github.com/looker-open-source/looker_deployer/files/8443272/ldeploy-export-error.txt)

So I am suspecting some kind of firewall issue.  Egress is wide open.
Do I need to open specific ports for ingress for ldeploy to work from GCP?  I don't see anything in the doc with respect to this.

**Comment by AdamMinton** [comment]
Hey @scboyce,

I think it sounds like a networking...can you try the following two commands from the GCP Instance? The first one will pull the headers, I would assume that it would say it cannot resolve the host if it can't connect to the instance. The second one will return an access token, this will test if you're able to work with the Looker API.

`curl -I http://www.instance.cloud.looker.com`

`curl -d "client_id=xxxxxxx&client_secret=yyyyyyy" https://instance.cloud.looker.com:443/login`

**Comment by scboyce** [comment]
Hey Adam, thanks for reply.
Both commands succeed.
The first returns "HTTP/1.1 303 See Other" among more messages, all look OK.
The second returns nothing.
Here is another interesting detail.  When I attempt to extract a folder with one dashboard and no subfolders, it succeeds.  it only fails when I try to export from the top level shared folder (1).
Also when I watch netstat in another window, I see all outgoing comms on 443 and incoming comms on many rotating ports.
I can see some back and forth, including ACK, but after about 4 or 5 rounds to messages it hangs on SYN_SENT.  So either the message is getting blocked or mangled on the way out.  There is no way for me to know if the API got that last message.
I agree this sounds like something in our network with respect to outgoing packets.  I have raised an internal ticket with our network engineers.  As long as I don't need to open more ports, I am convincing myself this is on our side.

**Comment by jannarobertson-bytecode** [comment]
@scboyce thank you for the update; we will be closing out the issue, as it sounds internal/networking, but please open another issue if you need any more assistance!
