### ISSUE TITLE
Getting an undefined: method 'space error

### ISSUE THREAD

**Issue by bobenauf** [looker-open-source/looker_deployer#79]
Has anything changed for looker_deployer for api 4.0? I am getting this error when I try to export my dashboards from the dev environment:
options: {"debug"=>true, "host"=>"revegydev.looker.com", "port"=>"19999", "ssl"=>true, "verify_ssl"=>false, "timeout"=>60, **Removed Client ID and Secret**
"dir"=>"content41122/Shared"}
API 3.1 available? true
connecting to ["api_endpoint=>https://revegydev.looker.com:19999/api/4.0", "connection_options=>{:ssl=>{:verify=>false}, :request=>{:timeout=>60}}", "user_agent=>Gazer 0.2.43", "client_id=>Remove", "client_secret=>*********"]
check for connectivity: true
verify authentication: true
logout
Traceback (most recent call last):
        18: from /usr/local/bin/gzr:23:in `<main>'
        17: from /usr/local/bin/gzr:23:in `load'
        16: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/exe/gzr:36:in `<top (required)>'
        15: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        14: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        13: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        12: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        11: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
        10: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
         9: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         8: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         7: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         6: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space.rb:80:in `export'
         5: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:49:in `execute'
         4: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/modules/session.rb:207:in `with_session'
         3: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:81:in `block in execute'
         2: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/commands/space/export.rb:87:in `process_space'
         1: from /var/lib/gems/2.5.0/gems/gazer-0.2.43/lib/gzr/modules/space.rb:65:in `query_space'
/var/lib/gems/2.5.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client/dynamic.rb:105:in `method_missing': undefined method `space' for #<LookerSDK::Client:0x000055fccc55f338> (NoMethodError)

Here is the line that I am running: ldeploy content export --env dev --folders 212 --local-target ./content41122/ --debug

**Comment by bobenauf** [comment]
I need to push client's dashboards to production. Do you know of work around for the above issue that I am having?

**Comment by michaelcramer** [comment]
@bobenauf I think this is due to your gazer gem being out of date.  
Please try updating the gazer gem: `gem install gazer`
And uninstall the old version: `gem uninstall gazer --version 0.2.43`
After updating, you can verify the latest version with `gem list` and you should see `gazer (0.2.54)`

**Comment by bobenauf** [comment]
Thanks Michael, I will try that

**Comment by jsnod** [comment]
@michaelcramer We ran into this same issue using the pre-built Dockerhub image `jcpistell/looker_deployer`. Unfortunately we don't have access to that to update the gem, and that image hasn't been updated in over two years. How can we get an updated image built at Dockerhub?

**Comment by maurk851** [comment]
> @michaelcramer We ran into this same issue using the pre-built Dockerhub image `jcpistell/looker_deployer` (as described in the README). Unfortunately we don't have access to that to update the gem, and that image hasn't been updated in over two years. How can we get an updated image built at Dockerhub?
> 
> ```
> /var/lib/gems/2.5.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client/dynamic.rb:105:in `method_missing': undefined method `space' for #<LookerSDK::Client:0x000055815147d1a0> (NoMethodError)
> 	from /var/lib/gems/2.5.0/gems/gazer-0.2.41/lib/gzr/modules/space.rb:65:in `query_space'
> 	from /var/lib/gems/2.5.0/gems/gazer-0.2.41/lib/gzr/commands/space/export.rb:87:in `process_space'
> 	from /var/lib/gems/2.5.0/gems/gazer-0.2.41/lib/gzr/commands/space/export.rb:81:in `block in execute'
> 	from /var/lib/gems/2.5.0/gems/gazer-0.2.41/lib/gzr/modules/session.rb:207:in `with_session'
> 	from /var/lib/gems/2.5.0/gems/gazer-0.2.41/lib/gzr/commands/space/export.rb:49:in `execute'
> 	from /var/lib/gems/2.5.0/gems/gazer-0.2.41/lib/gzr/commands/space.rb:80:in `export'
> 	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
> 	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
> 	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
> 	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
> 	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
> 	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
> 	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
> 	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
> 	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
> 	from /var/lib/gems/2.5.0/gems/gazer-0.2.41/exe/gzr:36:in `<top (required)>'
> 	from /usr/local/bin/gzr:23:in `load'
> 	from /usr/local/bin/gzr:23:in `<main>'
> ```

You just need to add to the Dockerfile the line `gem install gazer`
```
FROM jcpistell/looker_deployer:latest
RUN gem install gazer
COPY looker.ini /
```

**Comment by ddaugherty** [comment]
Hello @jsnod, 

Did you have a chance to try adding the `RUN gem install gazer` line to a DOCKERFILE based on jcpistell/looker_deployer:latest as suggested by maurk851 above?   

If you are still having an issue, please reply to this comment, otherwise it will be marked closed in 3 days.

Thanks.

**Comment by jsnod** [comment]
> Did you have a chance to try adding the `RUN gem install gazer` line to a DOCKERFILE based on jcpistell/looker_deployer:latest as suggested by maurk851 above?

@ddaugherty Yep, it worked, thanks! How can we get it baked into `jcpistell/looker_deployer` to save on build time? Any plans for an official `looker-open-source/looker_deployer`?

**Comment by jannarobertson-bytecode** [comment]
@jsnod we would suggest that you build the image locally and run it.  Not on the roadmap atm for an official Deployer, but appreciate the upvote!
