### ISSUE TITLE
Getting error while trying to deploy dashboard

### ISSUE THREAD

**Issue by shcsd-krigo** [looker-open-source/looker_deployer#96]
Getting following error while trying to deploy dashboard through github actions. We have self hosted github runners based on python:3.8-slim build with gazer and looker-deployer installed. We had no problems in exporting the data. If we run the same process locally, with everything being same, we are not getting any errors.

ldeploy content import --env dev --ini /app/looker.ini --debug  --dashboards "deployfolder/Shared/Clinical/Clinical Effectiveness/Dashboard_9_CMS OP-22.json"
{"levelname": "DEBUG", "module": "deploy_content", "funcName": "main", "message": "ini file", "ini": "/app/looker.ini", "timestamp": "2022-09-22T17:48:51.109751Z"}
{"levelname": "DEBUG", "module": "deploy_content", "funcName": "send_content", "message": "Deploying dashboards", "dashboards": 
["deployfolder/Shared/Clinical/Clinical Effectiveness/Dashboard_9_CMS OP-22.json"], "timestamp": "2022-09-22T17:48:51.110706Z"} 
{"levelname": "DEBUG", "module": "deploy_content", "funcName": "send_content", "message": "working dashboard", "dashboard": "deployfolder/Shared/Clinical/Clinical Effectiveness/Dashboard_9_CMS OP-22.json", "timestamp": "2022-09-22T17:48:51.110836Z"}       
Traceback (most recent call last):
  File "/usr/local/bin/ldeploy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/looker_deployer/cli.py", line 46, in main
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/looker_deployer/commands/deploy_content.py", line 306, in main
    send_content(
  File "/usr/local/lib/python3.8/site-packages/looker_deployer/commands/deploy_content.py", line 268, in send_content
    deploy_content("dashboard", dash, sdk, env, ini, debug)
  File "/usr/local/lib/python3.8/site-packages/looker_deployer/commands/deploy_content.py", line 215, in deploy_content
    a, b, c = dirs.partition(target_base)
TypeError: must be str, not NoneType

**Comment by ddaugherty** [comment]
Hello @shcsd-krigo 

This issue would occur in version v.3.7 but should be corrected in the latest update.   

Please update to looker-deployer version 0.3.8 if you have not already.   

If the issue is still occurring in ldeploy -v 0.3.8+, please let us know. 

Thank you.
@ddaugherty

**Comment by jannarobertson-bytecode** [comment]
@shcsd-krigo Please re-open the issue if you're still experiencing it after updating to looker-deployer version 0.3.8.  Thank you!
