### ISSUE TITLE
ERROR: Dashboard already exists in space 739

### ISSUE THREAD

**Issue by Rutvik1806** [looker-open-source/looker_deployer#99]
We are using the below Ldeploy script for migrating our Dashboards from one environment to another which was working fine previously and is able to update the dashboard in the destination. but now it is giving the below error.

Error:
**ERROR: Dashboard already exists in space 739**

Command:
**ldeploy content import --env destinationEnv --ini lookerEnvFile --debug --recursive --folders /sourceFolderPath --target-folder destinationFolderPath**

**Comment by abhirupc88** [comment]
We are getting the same, in looker 22.16 v

**Comment by AdamMinton** [comment]
Unsure I'm able to replicate. I believe this is probably more of an issue with Gazer given the error message. Generally the [error message](https://github.com/looker-open-source/gzr/blob/main/lib/gzr/commands/dashboard/mv.rb#L53) is inclusive of using --force to overwrite. The commands issued by Looker Deployer should always include --force.

Can you provide the version of Looker Deployer you are running?
Can you provide the version of Gazer you are running?
Can you attempt just using gazer to move the dashboard that is erroring to see if Looker Deployer or Gazer issue?
Can you verify if this dashboard has a merged result tile?

**Comment by jannarobertson-bytecode** [comment]
@Rutvik1806 @abhirupc88 Could you please let us know if this remains an issue for you?  If so, please provide the following per @AdamMinton's request:

- Can you provide the version of Looker Deployer you are running?
- Can you provide the version of Gazer you are running?
- Can you attempt just using gazer to move the dashboard that is erroring to see if Looker Deployer or Gazer issue?
- Can you verify if this dashboard has a merged result tile?

This ticket will be closed at the end of next week if no response is received. Thank you!

**Comment by jannarobertson-bytecode** [comment]
@Rutvik1806 please reopen issue with responses to the above if you're able to replicate.
